version: "3.9"
services: 
  lean-rest:
    image: bartmaer/lean-rest 
    ports:
      - 8080:8080
    volumes:
      - ../lean-engine/src/test/resources/presentations:/presentations
  lean-react:
    image: bartmaer/lean-viewer
    ports: 
      - 3000:3000
